spring:
  application:
    name: movieclient

  cloud:
    loadbalancer:
      retry:
        retryable-status-codes: 404, 500
        retry-on-all-operations: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 1

eureka:
  client:
    register-with-eureka: false
    #    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka