GET http://localhost:8888/helloworldservice/default

###

GET http://localhost:8888/helloworldservice/de

###

POST http://localhost:8888/encrypt

Hello Spring Community!

###

POST http://localhost:8888/encrypt

Hallo Spring-Gemeinde!

###

POST http://localhost:8888/decrypt

98ac2c7a88ab8865c75414d1cf092d87c6327152c8634f714c3966518494a2bc5fd7800c941263dcb23f9268cdbc521f